# Generated by Django 4.2 on 2023-04-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_response_order_name_alter_response_order_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='response',
            name='order_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='response',
            name='order_phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='response',
            name='order_secname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество'),
        ),
    ]
