# Generated by Django 4.2 on 2023-04-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_response_options_alter_response_order_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='response',
            name='order_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='response',
            name='order_phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя'),
        ),
    ]
