# Generated by Django 4.2 on 2023-04-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_response_city_alter_response_order_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='order_phone',
        ),
        migrations.AddField(
            model_name='response',
            name='age_r',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Возраст Аниматора'),
        ),
        migrations.AddField(
            model_name='response',
            name='city_r',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Населенный пункт Аниматора'),
        ),
        migrations.AddField(
            model_name='response',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email заявителя'),
        ),
        migrations.AddField(
            model_name='response',
            name='email_r',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email Аниматора'),
        ),
        migrations.AddField(
            model_name='response',
            name='female_r',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия Аниматора'),
        ),
        migrations.AddField(
            model_name='response',
            name='gl1',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Глава 1'),
        ),
        migrations.AddField(
            model_name='response',
            name='gl2',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Глава 2'),
        ),
        migrations.AddField(
            model_name='response',
            name='gl3',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Глава 3'),
        ),
        migrations.AddField(
            model_name='response',
            name='gl4',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Глава 4'),
        ),
        migrations.AddField(
            model_name='response',
            name='gl5',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Глава 5'),
        ),
        migrations.AddField(
            model_name='response',
            name='job_r',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место работы/учебы Аниматора'),
        ),
        migrations.AddField(
            model_name='response',
            name='name_r',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя Аниматора'),
        ),
        migrations.AddField(
            model_name='response',
            name='order_female',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия заявителя'),
        ),
        migrations.AddField(
            model_name='response',
            name='ph1',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Ссылка на фото героя'),
        ),
        migrations.AddField(
            model_name='response',
            name='ph2',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Ссылка на материалы'),
        ),
        migrations.AddField(
            model_name='response',
            name='prof_r',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Профессия/род занятий Аниматора'),
        ),
        migrations.AddField(
            model_name='response',
            name='q1',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Что делает эту историю уникальной'),
        ),
        migrations.AddField(
            model_name='response',
            name='q2',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Продолжение истории'),
        ),
        migrations.AddField(
            model_name='response',
            name='q3',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Последователи'),
        ),
        migrations.AddField(
            model_name='response',
            name='q4',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Единичный ли случай'),
        ),
        migrations.AddField(
            model_name='response',
            name='region_r',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Регион Аниматора'),
        ),
        migrations.AddField(
            model_name='response',
            name='residents_r',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Количество жителей в Регионе'),
        ),
        migrations.AddField(
            model_name='response',
            name='secname_r',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество Аниматора'),
        ),
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Статус заявителя'),
        ),
        migrations.AddField(
            model_name='response',
            name='tel_r',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон Аниматора'),
        ),
        migrations.AddField(
            model_name='response',
            name='vk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Страница VK Аниматора'),
        ),
        migrations.AlterField(
            model_name='response',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Населенный пункт заявителя'),
        ),
        migrations.AlterField(
            model_name='response',
            name='order_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя заявителя'),
        ),
        migrations.AlterField(
            model_name='response',
            name='order_secname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество заявителя'),
        ),
    ]
