# Generated by Django 4.2 on 2023-04-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_response_tel_r'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='gl3',
        ),
        migrations.RemoveField(
            model_name='response',
            name='gl4',
        ),
        migrations.RemoveField(
            model_name='response',
            name='gl5',
        ),
        migrations.AddField(
            model_name='response',
            name='gl3_1',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Глава 3-1'),
        ),
        migrations.AddField(
            model_name='response',
            name='gl3_2',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Глава 3-2'),
        ),
        migrations.AddField(
            model_name='response',
            name='gl3_3',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Глава 3-3'),
        ),
        migrations.AddField(
            model_name='response',
            name='gl3_4',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Глава 3-4'),
        ),
        migrations.AddField(
            model_name='response',
            name='gl4_1',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Глава 4-1'),
        ),
        migrations.AddField(
            model_name='response',
            name='gl4_2',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Глава 4-2'),
        ),
        migrations.AddField(
            model_name='response',
            name='gl5_1',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Глава 5-1'),
        ),
        migrations.AddField(
            model_name='response',
            name='gl5_2',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Глава 5-2'),
        ),
        migrations.AlterField(
            model_name='response',
            name='tel_r',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон Аниматора'),
        ),
    ]
